### ISSUE TITLE
Group Chat Manager update

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-hyperty#45]
Update according to most [updated communication data model spec](https://github.com/reTHINK-project/specs/tree/master/datamodel/data-objects/communication)

**Comment by pchainho** [comment]
The update was done in "CommunicationObject-Upgrade" branch and it will be merged to develop branch before end of the week 5th May 2017. @reTHINK-project/wp5 the ones using this Hyperty pls make sure it is compliant with this version

**Comment by luistduarte** [comment]
In our case, On [dev-smart-contextual-assistance-app](https://github.com/reTHINK-project/dev-smart-contextual-assistance-app) we just need to do a [little change](https://github.com/reTHINK-project/dev-smart-contextual-assistance-app/commit/6566c193af2ef7e51b82206332ccd429d91a417e) to work using the new model instead of ``` obj.value.message ``` now we use ```obj.value.content```

**Comment by luistduarte** [comment]
it is done.
