### ISSUE TITLE
DTWebRTC update

### ISSUE THREAD

**Issue by sbecot** [reTHINK-project/dev-hyperty#53]
Seems that the registry connector has changed, so the Discovery is not working anymore, neither the model of the connection object. Thus, The DTWebRTC can work if you call a hyperty url but the search is not working anymore. Plus interoperability may be broken.

**Comment by sdruesedow** [comment]
Could you give me a hint what has been changed on the connection data model? On https://github.com/reTHINK-project/specs/tree/master/datamodel/data-objects/connection I only find the very old obsolete version.

**Comment by sdruesedow** [comment]
Is there a recent Connector installation in one of the testbeds that I can use as counterpart for tests?

**Comment by sbecot** [comment]
Seems that @jboulmal is more aware of it, but there is at least a discovery problem (the interface of the runtime has changed):
compare
https://github.com/reTHINK-project/dev-hyperty/blob/develop/src/connector/Connector.hy.js#L65
and
https://github.com/reTHINK-project/dev-hyperty/blob/develop/src/dtwebrtc/DTWebRTC.hy.js#L25
But there is also a datascheme modification.
You can probably test with hysmart catalogue.

**Comment by sdruesedow** [comment]
Thanks for the feedback. I'll check the discovery issue. Regarding the datascheme I noticed recent updates in the communication model, but not in the connection scheme. Since the DTWebRTC is not using the communication model, this should not affect its functionality.

**Comment by sdruesedow** [comment]
your'e right Simon. The communication model is used by the GroupChatManager hyperty that I'm using. According to Paulo the change in the scheme also affects the app, not just the hyperty. I'll check this.

**Comment by sdruesedow** [comment]
Updated the DTWebRTC hyperty and the app code incl. several changes to make the discovery work again. Also updated all testbed components to the latest released versions and did a small change on the nomatrix MN caused by RegistryConnector changes. Achieved interoperability of the rethink-dev.tlabscloud.com WebRTC part with the Connector on the hysmart testbed. The chat part is only interoperable with the hysmart-GroupChatManager in one direction, depending on which side has initiated the session. not clear yet why.

**Comment by pchainho** [comment]
working with last versions
